FROM node:22-alpine
RUN apk add rsync

ENV NODE_ENV=development

WORKDIR /node_cache/app
COPY package.json package-lock.json* .npmrc* ./
RUN npm i

WORKDIR /app
COPY . .

# No RUN because in dev, docker-compose's command is used instead
