FROM node:22-alpine AS base
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev git rsync

FROM base AS runner
ENV NODE_ENV=development

WORKDIR /node_cache/cms
COPY package.json package-lock.json* .npmrc* ./
RUN npm i

RUN apk add --no-cache curl
WORKDIR /cms
COPY . .

# No RUN due to docker-compose command
